### PR TITLE
Fix bug & support comment format

### LINKED ISSUE #129: NullPointerException while loading @Condition from the field behind
I found that if the `@Condition` declared by the configuration field in the part of the Config class depends on the field in the text behind, the field in the second text cannot be initialized, and if it happens to be an enum type, it is null if it is not initialized. Here is a simple example.

```java
package me.jaffe2718.test;
import eu.midnightdust.lib.config.EntryInfo;
import eu.midnightdust.lib.config.MidnightConfig;

public class TestCondition extends MidnightConfig {


    @Entry
    @Condition(requiredOption = "flag", requiredValue = "SHOW_A")
    public static int numberA = 0;

    @Entry
    @Condition(requiredOption = "flag", requiredValue = "SHOW_B")
    public static int numberB = 0;

    @Entry
    @Condition(requiredOption = "flag", requiredValue = "SHOW_C")
    public static int numberC = 0;

    /**
     * MidnightLib 1.9.2
     * Issues Description: Crash because of NullPointerException
     * <pre>
     *  Caused by: java.lang.NullPointerException
     * 	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
     * 	at java.base/java.util.ImmutableCollections$List12.indexOf(ImmutableCollections.java:597)
     * 	at java.base/java.util.ImmutableCollections$AbstractImmutableList.contains(ImmutableCollections.java:331)
     * 	at knot//eu.midnightdust.lib.config.EntryInfo.lambda$updateConditions$0(EntryInfo.java:86)
     * 	at java.base/java.util.Optional.ifPresent(Optional.java:178)
     * 	at knot//eu.midnightdust.lib.config.EntryInfo.updateConditions(EntryInfo.java:86)
     * 	at knot//eu.midnightdust.lib.config.MidnightConfig.lambda$loadValuesFromJson$7(MidnightConfig.java:224)
     * 	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:833)
     * 	at knot//eu.midnightdust.lib.config.MidnightConfig.loadValuesFromJson(MidnightConfig.java:219)
     * 	at knot//eu.midnightdust.lib.config.MidnightConfig.init(MidnightConfig.java:103)
     * 	at knot//me.jaffe2718.test.TestMod.onInitializeClient(TestMod.java:13)
     * 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:405)
     * 	... 8 more
     * 	</pre>
     *
     * 	Reason: The flag field is not initialized when the conditions of the previous fields are loaded, {@link MidnightConfig#loadValuesFromJson}
     * 	{@link EntryInfo#updateConditions()}<br>
     *
     * 	Solution: Initialize the flag field before the conditions of the previous fields are loaded.<br>
     *
     * 	<pre>
     *     entries.values().forEach((info) -> {
     *         if (info.field != null && info.entry != null) {
     *              info.value = info.field.get((Object)null) == null ?
     *                      info.defaultValue : info.field.get((Object)null);
     *              info.tempValue = info.toTemporaryValue();
     *         }
     *     });
     *     entries.values().forEach((info) -> {
     *         if (info.field != null && info.entry != null) {
     *             MinecraftClient.getInstance().submit(info::updateConditions);
     *         }
     *     }
     * 	</pre>
     */
    @Entry
    public static ShowFlag flag = ShowFlag.SHOW_A;

    public enum ShowFlag {
        SHOW_A,
        SHOW_B,
        SHOW_C,
    }

}
```

Possible solutions: Load all configuration items `EntryInfo` before updating the conditions
```java
     entries.values().forEach((info) -> {
         if (info.field != null && info.entry != null) {
              info.value = info.field.get((Object)null) == null ?
                      info.defaultValue : info.field.get((Object)null);
              info.tempValue = info.toTemporaryValue();
         }
     });
     entries.values().forEach((info) -> {
         if (info.field != null && info.entry != null && MinecraftClient.getInstance() ！= null) {
             MinecraftClient.getInstance().submit(info::updateConditions);  // use render thread to prevent IllegalAccessException 
         }
     }
```

### PR DESCRIPTION
**Pull request by Jaffe2718**
- fix #129
- use `Supplier<Object[]>` to format `@Comment`
    ```java
    @Comment(category = TEXT, name = "UTC Time: %s")
    public static final Supplier<Object[]> utcTime = () -> {  // use the return value to format the comment
        Date now = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
        return new Object[]{sdf.format(now)};
    };
    ```

### CODE REVIEW

**Comment by Jaffe2718** [comment]
Using I18N to format `@Comment` is also available:

```json
{
    "modid.midnightconfig.utcTime": "UTC Time: %s"
}
```

```java
@Comment(category = TEXT)
public static final Supplier<Object[]> utcTime = () -> {  // use the return value to format the comment
    Date now = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
    return new Object[]{sdf.format(now)};
};
```

**Comment by Motschen** [comment]
Awesome changes, tysm!
I'm currently in the middle of a gamejam, so I'll only have time to merge them at the end of this week :)

**Comment by Jaffe2718** [comment]
I think this format can be improved and simplified for user operations, please don't merge yet

**Comment by Jaffe2718** [comment]
Currently, formatted `@Comment` must marked with `final`, otherwise format will fail.

```java
    @Comment(category = TEXT, name = "§bUTC Time: %s")
    public static final Supplier<Object[]> utcTime = () -> {                     // use the return value to format the comment
        Date now = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
        return new Object[]{sdf.format(now)};
    };
    @Comment(category = TEXT, name = "OS: §6%s, Arch: §6%s")
    public static final String[] platformInfo = {
            System.getProperty("os.name"),
            System.getProperty("os.arch")
    };
    @Comment(category = TEXT, name = "Minecraft %s, %s mods loaded")
    public static final List<String> gameInfo = List.of(
        FabricLoader.getInstance().getRawGameVersion(),
        String.valueOf(FabricLoader.getInstance().getAllMods().size())
    );
```

image

File: src/main/java/eu/midnightdust/lib/config/EntryInfo.java [hunk 1]
```diff
@@ -70,7 +70,7 @@ public String toTemporaryValue() {
     public void updateFieldValue() {
         try {
             if (this.field.get(null) != value) MidnightConfig.entries.values().forEach(EntryInfo::updateConditions);
-            this.field.set(null, this.value);
+            if (this.entry != null) this.field.set(null, this.value);
```
Comment (Jaffe2718) [inline src/main/java/eu/midnightdust/lib/config/EntryInfo.java:73]: With this change, `final` is no longer necessary for `@Comment` field with formatting

```java
    @Comment(category = TEXT, name = "§bUTC Time: %s")
    public static Supplier<Object[]> utcTime = () -> {                     // use the return value to format the comment
        Date now = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
        return new Object[]{sdf.format(now)};
    };
    @Comment(category = TEXT, name = "OS: §6%s, Arch: §6%s")
    public static String[] platformInfo = {
            System.getProperty("os.name"),
            System.getProperty("os.arch")
    };
    @Comment(category = TEXT, name = "Minecraft %s, %s mods loaded")
    public static List<String> gameInfo = List.of(
        FabricLoader.getInstance().getRawGameVersion(),
        String.valueOf(FabricLoader.getInstance().getAllMods().size())
    );
```

File: src/main/java/eu/midnightdust/lib/config/MidnightConfig.java [hunk 2]
```diff
@@ -216,15 +217,20 @@ public void loadValuesFromJson() {
...
 
-        entries.values().forEach(info -> {
+        entries.values().forEach((info) -> {
             if (info.field != null && info.entry != null) {
                 try {
-                    info.value = info.field.get(null) == null ? info.defaultValue : info.field.get(null);
+                    info.value = info.field.get(null) == null ?
+                            info.defaultValue : info.field.get(null);
                     info.tempValue = info.toTemporaryValue();
-                    info.updateConditions();
```
Comment (Motschen) [inline src/main/java/eu/midnightdust/lib/config/MidnightConfig.java:224]: Why did you add a second `forEach` loop instead of just replacing this one line with the submit call?

Comment (Jaffe2718) [reply src/main/java/eu/midnightdust/lib/config/MidnightConfig.java:224]: > Why did you add a second `forEach` loop instead of just replacing this one line with the submit call?

That is the key to resolve the issues #129 .

If the `@Condition` of the config field rely on other fields defined behind and you call `info.updateConditions();`, it will cause `NullPointerException` because the `value` of dependent `EntryInfo` hasn't been initialized yet. So I split it into two loops, each `EntryInfo`s can initialize its `value` in the first loop, and update all `@Condition`s in the second loop

And the reason I use `Minecraft.getInstance().submit(info::updateConditions);` is that updating the status of widgets cannot accessed besides `Render` thread, otherwise, it will raise an `IllegalAccessException`

Comment (Motschen) [reply src/main/java/eu/midnightdust/lib/config/MidnightConfig.java:224]: Thanks for the explanation, makes total sense!
